function results = easy_sample(model, spikes, initial_assignments, config)
    % Save copy of initial assignments
    inits = initial_assignments;

    % Draw annealed Gibbs samples
    [model,assignments, anneal_assignment_hist, anneal_log_p_hist, anneal_latent_event_hist, anneal_globals_hist] = ...
        annealed_gibbs(model, spikes, inits, config.num_anneals, config.samples_per_anneal, config.max_temperature, config.split_merge_moves_during_anneal, config.split_merge_window, config.save_every_during_anneal, true);

    % Draw regular Gibbs samples
    [~,assignments, assignment_hist, log_p_hist, latent_event_hist, globals_hist] = ...
        gibbs_sample(model, spikes, assignments, config.samples_after_anneal, config.split_merge_moves_after_anneal, config.split_merge_window, config.save_every_after_anneal, true);

    % Return results in a structure
    results = struct(...
        'initial_assignments', {inits}, ...
        'anneal_assignment_hist', {anneal_assignment_hist}, ...
        'anneal_log_p_hist', {anneal_log_p_hist}, ...
        'anneal_latent_event_hist', {anneal_latent_event_hist}, ...
        'anneal_globals_hist', {anneal_globals_hist}, ...
        'final_assignments', {assignments}, ...
        'assignment_hist', {assignment_hist}, ...
        'latent_event_hist', {latent_event_hist}, ...
        'globals_hist', {globals_hist}, ...
        'log_p_hist', {log_p_hist} ...
    );
end
